const REDUCER = 'categories';

export const ON_ADD_CATEGORY = `${REDUCER}/ON_ADD_CATEGORY`;

export const ADD_CATEGORY_REQUEST = `${REDUCER}/ADD_CATEGORY_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${REDUCER}/ADD_CATEGORY_SUCCESS`;
export const ADD_CATEGORY_FAILURE = `${REDUCER}/ADD_CATEGORY_FAILURE`;

export default REDUCER;