const REDUCER = 'categories';

export const ON_ADD_CATEGORY = `${REDUCER}/ON_ADD_CATEGORY`;
export const GET_CATEGORIES = `${REDUCER}/GET_CATEGORIES`;

export const ADD_CATEGORY_REQUEST = `${REDUCER}/ADD_CATEGORY_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${REDUCER}/ADD_CATEGORY_SUCCESS`;
export const ADD_CATEGORY_FAILURE = `${REDUCER}/ADD_CATEGORY_FAILURE`;

export const GET_CATEGORIES_REQUEST = `${REDUCER}/GET_CATEGORIES_REQUEST`;
export const GET_CATEGORIES_SUCCESS = `${REDUCER}/GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_FAILURE = `${REDUCER}/GET_CATEGORIES_FAILURE`;

export default REDUCER;