const REDUCER = 'expenses';

export const ON_ADD_EXPENSE = `${REDUCER}/ON_ADD_EXPENSE`;
export const ON_EDIT_EXPENSE = `${REDUCER}/ON_EDIT_EXPENSE`;
export const GET_EXPENSE = `${REDUCER}/GET_EXPENSE`;
export const DELETE_EXPENSE = `${REDUCER}/DELETE_EXPENSE`;

export const ADD_EXPENSE_REQUEST = `${REDUCER}/ADD_EXPENSE_REQUEST`;
export const ADD_EXPENSE_SUCCESS = `${REDUCER}/ADD_EXPENSE_SUCCESS`;
export const ADD_EXPENSE_FAILURE = `${REDUCER}/ADD_EXPENSE_FAILURE`;

export const GET_EXPENSES_REQUEST = `${REDUCER}/GET_EXPENSES_REQUEST`;
export const GET_EXPENSES_SUCCESS = `${REDUCER}/GET_EXPENSES_SUCCESS`;
export const GET_EXPENSES_FAILURE = `${REDUCER}/GET_EXPENSES_FAILURE`;

export default REDUCER;